In [1]:
import torch
torch.__version__

'2.11.0'

In [3]:
scalar = torch.tensor(3.)
scalar 

tensor(3.)

In [4]:
scalar.item()

3.0

In [10]:
vector = torch.tensor([3., 7.])
print(vector)
print(vector.ndim)

tensor([3., 7.])
1


In [12]:
vector.shape

torch.Size([2])

In [13]:
mat = torch.tensor([[7.,8.],
                    [9.,10.]])
mat

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [14]:
print(mat.ndim)
print(mat.shape)

2
torch.Size([2, 2])


In [17]:
random_tensor = torch.rand((3,4), dtype=torch.float64)
random_tensor, random_tensor.dtype

(tensor([[0.0088, 0.1485, 0.5951, 0.0255],
         [0.5128, 0.3499, 0.6189, 0.4255],
         [0.7063, 0.3426, 0.2308, 0.0809]], dtype=torch.float64),
 torch.float64)

In [19]:
#common img shape is [224, 224, 3] (height, width, color_channels)
rnd_img_tensor = torch.rand(224, 224, 3)
rnd_img_tensor.shape, rnd_img_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [23]:
torch.zeros(3,3)
#a.dtype

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#like
ten_zeros = torch.zeros_like(zero_to_ten)
oness = torch.ones_like(zero_to_ten)
ten_zeros, oness

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [32]:
sample_tensor = torch.tensor([3., 6., 9.],
                             dtype=None, #defaults to none(float32)
                             device=None, #def None(uses default tensor type can switch to cudam mps
                             requires_grad=False) # if True, operations on this will be recorded

sample_tensor.shape, sample_tensor.dtype, sample_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [33]:
#from float 32 to float16 torch.half(t)

In [34]:
some_tensor = torch.rand(3,4)

#details
print(some_tensor)
print(f"shape: {some_tensor.shape}")
print(f"Datatype: {some_tensor.dtype}")
print(f"device tensor stored on: {some_tensor.device}")

tensor([[0.5561, 0.0751, 0.1708, 0.8976],
        [0.4269, 0.5923, 0.7824, 0.4204],
        [0.3851, 0.0516, 0.3375, 0.7162]])
shape: torch.Size([3, 4])
Datatype: torch.float32
device tensor stored on: cpu


In [35]:
tensor = torch.tensor([1., 2., 3.,])
tensor, tensor+10, tensor-10, tensor*10, tensor/10, tensor**2, tensor//3, tensor%2
#can also use tensor.multiply(t,10)

(tensor([1., 2., 3.]),
 tensor([11., 12., 13.]),
 tensor([-9., -8., -7.]),
 tensor([10., 20., 30.]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([1., 4., 9.]),
 tensor([0., 0., 1.]),
 tensor([1., 0., 1.]))

In [36]:
tensor = torch.tensor([1.,2.,3.])
tensor*tensor

tensor([1., 4., 9.])

In [37]:
torch.matmul(tensor,tensor) #matrix mult

tensor(14.)

In [38]:
#also @
tensor @ tensor
#builtin torch.matmul(t1, t2) is faster

tensor(14.)

In [39]:
%%time
#matrix mult by hand

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 1.4 ms, sys: 2.92 ms, total: 4.32 ms
Wall time: 2.55 ms


tensor(14.)

In [43]:
%%time

torch.matmul(tensor, tensor)
#conside the shapes axb bxd => axd
#also this mult was a 1d not 1x3 1x3 will be ([[1,2,3]])

CPU times: user 189 μs, sys: 72 μs, total: 261 μs
Wall time: 224 μs


tensor(14.)

In [44]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:

# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [47]:
#torch.mm
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [48]:

# Since the linear layer starts with a random weights matrix, let's make it reproducible
torch.manual_seed(42)
# This uses matrix mutliplcation
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")


Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [51]:

# Create a tensor
x = torch.arange(0, 100, 10)
print(f"{x}\n")


print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [52]:

# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [63]:
x = torch.arange(1., 9.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [64]:
#Add an extra dimension
x_reshaped = x.reshape(1, 8)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [65]:
x_unsqueezed = x.unsqueeze(0)#0,1 dim
x_unsqueezed, x_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [66]:
z = x.view(2,2,2)
z
#suprising but changing z changes x

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [70]:
z[:,  0]
z[:, 0] = 5 
z, x
#yuppp

(tensor([[[5., 5.],
          [3., 4.]],
 
         [[5., 5.],
          [7., 8.]]]),
 tensor([5., 5., 3., 4., 5., 5., 7., 8.]))

In [74]:
# Stack tensors on top of each other
x_stacked_dim1 = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked_dim0 = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked_dim1, x_stacked_dim0

(tensor([[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.]]),
 tensor([[5., 5., 3., 4., 5., 5., 7., 8.],
         [5., 5., 3., 4., 5., 5., 7., 8.],
         [5., 5., 3., 4., 5., 5., 7., 8.],
         [5., 5., 3., 4., 5., 5., 7., 8.]]))

In [75]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 5., 3., 4., 5., 5., 7., 8.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([5., 5., 3., 4., 5., 5., 7., 8.])
New shape: torch.Size([8])


In [76]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 5., 3., 4., 5., 5., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 5., 3., 4., 5., 5., 7., 8.]])
New shape: torch.Size([1, 8])


In [77]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [78]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [81]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [82]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]


tensor([[2, 5, 8]])

In [83]:

# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [84]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]


tensor([1, 2, 3])

In [85]:
x[:,:,0]

tensor([[1, 4, 7]])

In [86]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))


Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).